title = 'ADK9 Antibody Against AAV9'
xlabel = 'Antibody Concentration [ng/mL]'
ylabel = 'Transduction Efficiency (%)'
basic_stats.groupby = ['sample', 'conc_ng']
normalize.groupby = ['sample']
plot.groupby = ['sample']
figures.mcmc_show_nd50 = 1
figures.barplotylim = 0.4
figures.barplot_toffset = 0.002
figures.barplot_text_gap = 0.14


[meta]
path = "../data/plate_data/adk9.xlsx"
date = 2024-02-24

[expt]
cell_number = '1x10^5 cell/well'

moi = 100
capsid = 'AAV9'
plate = 'Plate 1'
incubation_time = '48 h'


#ADK9 amount
[block.3x1]
A1.conc_ng = 3.13
B1.conc_ng = 1.56
C1.conc_ng = 0.78
D1.conc_ng = 0.39
E1.conc_ng = 0.20
F1.conc_ng = 0.10
G1.conc_ng = 0.05

H4.no_antibody_control = 1  # antibody-free control
H4.conc_ng = 0
H7.negative_control = 1  # no virus, no serum, only cells

#protocol
[block.3x7]
A1.sample = 'ADK9'





